Try to fix `AdWidget requires Ad.load to be called...` error
Error: `AdWidget requires Ad.load to be called before AdWidget is inserted into the tree. Error thrown.`
https://console.firebase.google.com/u/0/project/silgam-app/crashlytics/app/ios:com.seunghyun.silgam/issues/76a32e46bd2599c15a6ff21a5c8fefa7?time=last-ninety-days&versions=1.9.1%20(115);1.9.1%20(114)